### ISSUE TITLE
Links to articles invalid

### ISSUE THREAD

**Issue by Andrew-Pynch** [jichu4n/basic_wm#4]
Hello sir, I can't appear to access the entirety of your series because the links to parts 2 and 3 are broken. Is there another place I can read your articles? Would love to follow along to help me with my implementation of re-creating Microsoft's power toys fancyzones :-)

**Comment by jichu4n** [comment]
Hi Andrew! Thanks for the note - missed this during my recent blog migration.

Should be fixed now: https://jichu4n.com/posts/how-x-window-managers-work-and-how-to-write-one-part-ii/
